name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hi there! It's your first time opening an issue here... Enjoy your stay I guess"
        pr-message: "Hi there! It's your first time opening a PR here... Enjoy your stay I guess"
